/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalendarPost {
  'id' : bigint,
  'postTime' : bigint,
  'theme' : string,
  'title' : string,
  'contentType' : ContentCategory,
  'objective' : string,
  'storyId' : [] | [bigint],
  'createdAt' : bigint,
  'videoIdeaId' : [] | [bigint],
  'lastUpdated' : bigint,
  'postStatus' : PostStatus,
  'engagementGoal' : string,
  'platform' : string,
  'suggestedCaptions' : Array<string>,
  'contentStyle' : ContentStyle,
  'hookId' : [] | [bigint],
  'trendId' : [] | [bigint],
  'format' : string,
}
export type ContentCategory = { 'trend' : null } |
  { 'challenge' : null } |
  { 'other' : string } |
  { 'entertainment' : null } |
  { 'storytime' : null } |
  { 'educational' : null } |
  { 'productDemo' : null } |
  { 'tutorial' : null } |
  { 'testimonial' : null } |
  { 'behindTheScenes' : null };
export type ContentStyle = { 'qna' : null } |
  { 'review' : null } |
  { 'comparison' : null } |
  { 'voiceover' : null } |
  { 'other' : string } |
  { 'interview' : null } |
  { 'meme' : null } |
  { 'animation' : null } |
  { 'skit' : null } |
  { 'caseStudy' : null } |
  { 'bRoll' : null } |
  { 'talkingHead' : null };
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'expert' : null } |
  { 'medium' : null };
export type HookType = { 'trend' : null } |
  { 'challenge' : null } |
  { 'other' : string } |
  { 'painPoint' : null } |
  { 'curiosity' : null } |
  { 'shockValue' : null } |
  { 'quickWin' : null } |
  { 'story' : null } |
  { 'nostalgia' : null } |
  { 'authority' : null } |
  { 'contrarian' : null };
export type PostStatus = { 'scheduled' : null } |
  { 'published' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export interface StoryIdea {
  'id' : bigint,
  'endGoal' : string,
  'deliveryStyle' : ContentStyle,
  'supportingPoints' : Array<string>,
  'createdAt' : bigint,
  'audience' : string,
  'engagementRate' : [] | [bigint],
  'mainText' : string,
  'conversionRate' : [] | [bigint],
  'hookId' : bigint,
  'isViral' : boolean,
  'trendId' : bigint,
  'videoId' : bigint,
}
export interface Trend {
  'id' : bigint,
  'title' : string,
  'viralPotential' : bigint,
  'difficulty' : Difficulty,
  'createdAt' : bigint,
  'soundClip' : [] | [string],
  'description' : string,
  'referenceVideos' : Array<string>,
  'isActive' : boolean,
  'relevanceScore' : bigint,
  'trendScore' : bigint,
  'category' : TrendCategory,
  'analyzedHashtagPerformance' : Array<string>,
  'lastChecked' : bigint,
  'trendAlertSource' : string,
}
export type TrendCategory = { 'music' : null } |
  { 'soundEffect' : null } |
  { 'topic' : null } |
  { 'algorithmShift' : null } |
  { 'hashtag' : null } |
  { 'challenge' : null } |
  { 'other' : string } |
  { 'creatorStyle' : null } |
  { 'editTechnique' : null } |
  { 'meme' : null } |
  { 'series' : null } |
  { 'visualEffect' : null } |
  { 'product' : null } |
  { 'format' : null };
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'createdAt' : bigint,
  'contentCategory' : Array<ContentCategory>,
  'contentStyle' : Array<ContentStyle>,
  'targetAudience' : string,
  'goals' : string,
  'niche' : string,
  'postingFrequency' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoHook {
  'id' : bigint,
  'content' : string,
  'performanceRating' : [] | [bigint],
  'difficulty' : Difficulty,
  'createdAt' : bigint,
  'videoCategory' : ContentCategory,
  'hookType' : HookType,
  'isViral' : boolean,
  'trendId' : bigint,
  'videoId' : bigint,
}
export interface VideoIdea {
  'id' : bigint,
  'complexity' : Difficulty,
  'lastEdited' : bigint,
  'insights' : Array<string>,
  'title' : string,
  'contentType' : ContentCategory,
  'createdAt' : bigint,
  'adReadPotential' : boolean,
  'engagementRate' : [] | [bigint],
  'referenceVideos' : Array<string>,
  'suggestedCaptions' : Array<string>,
  'contentStyle' : ContentStyle,
  'hookType' : HookType,
  'length' : string,
  'conversionRate' : [] | [bigint],
  'trendId' : bigint,
  'objectives' : string,
  'editingTips' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserCalendarPosts' : ActorMethod<[], Array<CalendarPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStoryIdeas' : ActorMethod<[], Array<StoryIdea>>,
  'getUserTrends' : ActorMethod<[], Array<Trend>>,
  'getUserVideoHooks' : ActorMethod<[], Array<VideoHook>>,
  'getUserVideoIdeas' : ActorMethod<[], Array<VideoIdea>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCalendarPost' : ActorMethod<[CalendarPost], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveStoryIdea' : ActorMethod<[StoryIdea], undefined>,
  'saveTrend' : ActorMethod<[Trend], undefined>,
  'saveVideoHook' : ActorMethod<[VideoHook], undefined>,
  'saveVideoIdea' : ActorMethod<[VideoIdea], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];